apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: PreSync
spec:
  destination:
    name: ""
    namespace: swdb
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 17.3.5
    chart: redis
  project: swdb
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
